Updated to latest lfscript

diff --git a/factory/fetch b/factory/fetch
--- a/factory/fetch
+++ b/factory/fetch
@@ -2,110 +2,247 @@
 set -E
 trap error ERR
 
+DEFAULT_VERSION_LFS="10727"
+DEFAULT_VERSION_BLFS="13994"
+
+SCRIPTS_DIR="NEW_SCRIPTS"
+
+# Error handler
 error() {
-  echo "*** FAILURE ***" 1>&2
-  exit 1
+    echo "*** FAILURE ***" 1>&2
+    exit 1
 }
 
+# Make the 'which' command available, even if the host system does not have it.
+which() {
+    type -pa "$@" | head -n 1 ; return ${PIPESTATUS[0]}
+}
+
+# Fetch stable LFS book
 getStableLFS() {
-  local DOWNLOAD="http://www.linuxfromscratch.org/lfs/downloads"
+    local DOWNLOAD="http://www.linuxfromscratch.org/lfs/downloads"
 
-  if [ ! -r "books/LFS-BOOK-${VERSION}-XML.tar.bz2" ]; then
-    echo "*** Downloading LFS ${VERSION}..."
-    mkdir -p books
-    cd books
-    wget "${DOWNLOAD}/${VERSION}/LFS-BOOK-${VERSION}-XML.tar.bz2" 2> /dev/null
-    cd ../
-  fi
+    if [ ! -r "books/LFS-BOOK-${VERSION}.tar.bz2" ] &&
+       [ ! -r "books/LFS-BOOK-${VERSION}-XML.tar.bz2" ]; then
+        echo "*** Downloading LFS ${VERSION}..." >&2
+        mkdir -p books
+        cd books
+       (wget "${DOWNLOAD}/${VERSION}/LFS-BOOK-${VERSION}.tar.bz2" ||
+                wget "${DOWNLOAD}/${VERSION}/LFS-BOOK-${VERSION}-XML.tar.bz2") \
+                        2> /dev/null
+        cd ../
+    fi
 
-  echo "*** Extracting LFS ${VERSION}..."
-  rm -rf tmp patched-xml/lfs-${VERSION}-xml
-  mkdir tmp
-  mkdir -p patched-xml
-  cd tmp
-  tar xf ../books/LFS-BOOK-${VERSION}-XML.tar.bz2
-  mv * ../patched-xml/lfs-${VERSION}-xml
-  cd ../
-  rm -rf tmp
-}
-
-getStableBLFS() {
-  echo "*** Stable BLFS books are not supported at this time. ***"
-  exit 1
-}
-
-getSvn() {
-  if [ ! -r "books/${BOOK_L}-svn-${VERSION}.tar.bz2" ]; then
-    echo "*** Downloading ${BOOK_U} development revision ${VERSION}..."
-    mkdir -p books
-    rm -rf tmp
+    echo "*** Extracting LFS ${VERSION}..." >&2
+    rm -rf tmp patched-xml/lfs-${VERSION}-xml
     mkdir tmp
+    mkdir -p patched-xml
     cd tmp
-    svn export ${SVN_URL} -r ${VERSION} > /dev/null
-
-    echo "*** Archiving ${BOOK_U} development revision ${VERSION} for later use..."
-    mv * ${BOOK_L}-${VERSION}-xml
-    tar jcf ../books/${BOOK_L}-svn-${VERSION}.tar.bz2 *
+    if [ -r "../books/LFS-BOOK-${VERSION}.tar.bz2" ]; then
+        tar xf ../books/LFS-BOOK-${VERSION}.tar.bz2
+    else
+        tar xf ../books/LFS-BOOK-${VERSION}-XML.tar.bz2
+    fi
+    mv * ../patched-xml/lfs-${VERSION}-xml
     cd ../
     rm -rf tmp
-  fi
-
-  echo "*** Extracting ${BOOK_U} development revision ${VERSION}..."
-  rm -rf patched-xml/${BOOK_L}-${VERSION}-xml
-  mkdir -p patched-xml
-  cd patched-xml
-  tar xf ../books/${BOOK_L}-svn-${VERSION}.tar.bz2
-  cd ../
 }
 
-# Book selection
+# Fetch stable BLFS book
+getStableBLFS() {
+    echo "ERROR: Stable BLFS books are not supported." >&2
+    exit 1
+}
+
+# Fetch development (B)LFS book
+getSvn() {
+    local SVN_URL="svn://svn.linuxfromscratch.org/${BOOK_U}/trunk"
+
+    if [ "${VERSION}" == "svn" ]; then
+        echo -n "*** Looking up current revision of ${BOOK_U}... " >&2
+        VERSION="$(svn info ${SVN_URL} | grep Revision | cut -d' ' -f2)"
+        echo "${VERSION}" >&2
+        echo "${VERSION}"
+        return
+    fi
+
+    if [ ! -r "books/${BOOK_L}-svn-${VERSION}.tar.bz2" ]; then
+        echo -n "*** Downloading ${BOOK_U} SVN revision ${VERSION}... " >&2
+        mkdir -p books
+        rm -rf tmp
+        mkdir tmp
+        cd tmp
+        svn export ${SVN_URL} -r ${VERSION} > /dev/null
+        echo "OK" >&2
+
+        echo -n "*** Archiving ${BOOK_U} SVN r${VERSION} for later use... " >&2
+        mv * ${BOOK_L}-${VERSION}-xml
+        tar jcf ../books/${BOOK_L}-svn-${VERSION}.tar.bz2 *
+        cd ../
+        rm -rf tmp
+        echo "OK" >&2
+    fi
+
+    echo -n "*** Extracting ${BOOK_U} SVN revision ${VERSION}... " >&2
+    rm -rf patched-xml/${BOOK_L}-${VERSION}-xml
+    mkdir -p patched-xml
+    cd patched-xml
+    tar xf ../books/${BOOK_L}-svn-${VERSION}.tar.bz2
+    cd ../
+    echo "OK" >&2
+}
+
+fetch() {
+    if [ "${VARIANT}" == "stable" ]; then
+        if [ "${BOOK_L}" == "lfs" ]; then
+            getStableLFS
+        else
+            getStableBLFS
+        fi
+    else
+        getSvn
+    fi
+
+    # Apply patch, created using:
+    # $ diff -rupN old/ new/ > diff.patch
+    if [ ! "${NOPATCH}" ]; then
+
+        # Detect patches dir
+        if [ -d "patches-${BOOK_L}/${VERSION}" ] &&
+                [ "$(ls patches-${BOOK_L}/${VERSION}/*.patch)" != "" ]; then
+            PATCHDIR="patches-${BOOK_L}/${VERSION}"
+        elif [ "$(ls patches-${BOOK_L}/*.patch)" != "" ]; then
+            PATCHDIR="patches-${BOOK_L}"
+        else
+           (echo "WARNING:";
+            echo "    There was no patch file found for ${BOOK_U} ${VERSION}.";
+            echo "    This means that you are probably generating scripts for";
+            echo "    un untested version of ${BOOK_L}.") 1>&2
+            return
+        fi
+
+        echo "*** Patching from directory '${PATCHDIR}'" >&2
+
+        if [ -r "${PATCHDIR}/${BOOK_L}-${VERSION}.patch" ]; then
+            PATCHLIST="${PATCHDIR}/${BOOK_L}-${VERSION}.patch"
+        else
+            PATCHLIST="$(ls ${PATCHDIR}/*.patch)"
+        fi
+
+
+
+        echo "*** Patching the XML sources:" >&2
+        pushd patched-xml/${BOOK_L}-${VERSION}-xml > /dev/null
+
+        for PATCH in ${PATCHLIST}; do
+            echo "--- $(basename ${PATCH}) ---" >&2
+            patch -f -p1 < ../../${PATCH} || echo -n ''
+        done
+
+       popd > /dev/null
+    fi
+}
+
+factory() {
+    if [ "${BOOK_L}" == "blfs" ]; then
+        rm -rf ${SCRIPTS_DIR}/{extras,contrib}
+        mkdir -p ${SCRIPTS_DIR}/{extras,contrib}
+    fi
+    rm -rf ${SCRIPTS_DIR}/${BOOK_L}-${VERSION}{,-unchecked}
+    mkdir -p ${SCRIPTS_DIR}/${BOOK_L}-${VERSION}{,-unchecked}
+
+    fetch
+
+
+    case $(uname -m) in
+    i?86)
+        ARCH="i386"
+        ;;
+    *)
+        ARCH="$(uname -m)"
+        ;;
+    esac
+
+    JAVA="../lfc/build/vm-${ARCH}"
+    if [ "$(which java 2> /dev/null)" != "" ]; then
+        echo "*** Using host system java" >&2
+        JAVA="java"
+    fi
+
+    echo "*** Running ScriptFactoryII" >&2
+    SF_VERSION="r${VERSION}"
+    if [ "${VARIANT}" == "stable" ]; then
+        SF_VERSION="${VERSION} (stable)"
+    fi
+    ${JAVA} -cp ../lfc/build/libLFClass.jar org.lfscript.factory2.XMLFactory \
+            ${BOOK_L} patched-xml/${BOOK_L}-${VERSION}-xml \
+            ${SCRIPTS_DIR}/${BOOK_L}-${VERSION}-unchecked ${SF_VERSION} ${@}
+
+    rm -rf patched-xml
+
+    # Whitelist
+    if [ "${BOOK_L}" == "blfs" ] && [ -r whitelists/blfs-*.list ]; then
+        echo -n "*** Processing whitelist... " >&2
+        for f in $(cat whitelists/blfs-*.list | grep -v "^#"); do
+            mv ${SCRIPTS_DIR}/blfs-${VERSION}{-unchecked,}/${f} || echo -n ""
+        done
+        echo "OK" >&2
+    else
+        rm -rf ${SCRIPTS_DIR}/${BOOK_L}-${VERSION}
+        mv ${SCRIPTS_DIR}/${BOOK_L}-${VERSION}{-unchecked,}
+    fi
+}
+
+# Select book (argument 1)
 BOOK_L="${1}"
-if [ "${1}" == "lfs" ]; then
-  BOOK_U="LFS"
-elif [ "${1}" == "blfs" ]; then
-  BOOK_U="BLFS"
-else
-  echo "Select either 'lfs' or 'blfs'"
-  exit 1
-fi
-
-# Svn URL preparation
 if [ "${BOOK_L}" == "lfs" ]; then
-  SVN_URL="svn://svn.linuxfromscratch.org/LFS/trunk"
+    BOOK_U="LFS"
 elif [ "${BOOK_L}" == "blfs" ]; then
-  SVN_URL="svn://svn.linuxfromscratch.org/BLFS/trunk"
+    BOOK_U="BLFS"
+else
+    echo "ERROR: First argument must be either 'lfs' or 'blfs'." >&2
+    exit 1
+fi
+shift
+
+# Select version and determine variant (optional argument 2)
+VERSION="${1}"
+if [ "${VERSION}" ]; then
+    if [ "${VERSION}" == "nopatch" ]; then
+        VERSION=""
+    else
+        shift
+    fi
 fi
 
-# Version selection and download
-if [ "$(echo ${2} | grep '\.')" != "" ]; then
-  VERSION="${2}"
-  getStable${BOOK_U}
-else
-  if [ "${2}" == "" ]; then
-    echo "*** Looking up current revision of ${BOOK_U}..."
-    VERSION="$(svn info ${SVN_URL} | grep Revision | cut -d' ' -f2)"
-  else
-    VERSION="${2}"
-  fi
-
-  getSvn
+if [ "${VERSION}" == "" ] || [ "${VERSION}" == "default" ]; then
+    if [ "${BOOK_L}" == "lfs" ]; then
+        VERSION="${DEFAULT_VERSION_LFS}";
+    elif [ "${BOOK_L}" == "blfs" ]; then
+        VERSION="${DEFAULT_VERSION_BLFS}";
+    fi
 fi
 
-# Apply patch, created using:
-# $ diff -Naur old/ new/ > diff.patch
-if [ "${3}" != "nopatch" ] && [ "$(ls patches-${BOOK_L}/*.patch)" != "" ]; then
-    echo "*** Patching the XML sources"
-    pushd patched-xml/${BOOK_L}-${VERSION}-xml > /dev/null
-
-    for PATCH in $(ls ../../patches-${BOOK_L}/*.patch); do
-        echo "--- $(basename ${PATCH}) ---"
-        patch -p1 < ${PATCH}
-    done
-
-    popd > /dev/null
+if [ "$(echo ${VERSION} | grep '\.')" != "" ]; then
+    VARIANT="stable"
 else
- (echo "WARNING: There was no patch file found for ${BOOK_U} ${VERSION}." &&
-  echo "         This means that ScriptFactory is not guaranteed to deliver" &&
-  echo "         proper scripts using this source.") 1>&2
+    VARIANT="svn"
+    if [ "${VERSION}" == "" ] || [ "${VERSION}" == "svn" ]; then
+        VERSION="$(getSvn)"
+    fi
+fi
+
+# Opt out of patches (optional argument 3)
+NOPATCH=""
+if [ "${1}" == "nopatch" ]; then
+    NOPATCH="true"
+    shift
+fi
+
+# Select function
+if [ "${0}" == "fetch" ] || [ "${0}" == "./fetch" ]; then
+    fetch ${@}
+else
+    factory ${@}
 fi
 
diff --git a/lfscript b/lfscript
--- a/lfscript
+++ b/lfscript
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Linux From SCRIPT - Build a Linux operating system from sourcecode
-# Copyright (C) 2007-2012 Marcel van den Boer
+# Copyright (C) 2007-2014 Marcel van den Boer
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -235,8 +235,8 @@ topBanner() {
 
   # Versioned logo plate
   local v0="(bbla)(bbla)(bbla)                                           "
-  local v1="  (fblu)LINUX (fred)FROM SCRIPT (fyel)4         #2012-02-12  "
-  local v2="(bbla)(bbla)  Copyright 2010-2012 Marcel van den Boer(fwhi)  "
+  local v1="  (fblu)LINUX (fred)FROM SCRIPT (fyel)4         #2014-08-31  "
+  local v2="(bbla)(bbla)  Copyright 2010-2014 Marcel van den Boer(fwhi)  "
   local v3="(bbla)(bbla)(bbla)                                           "
 
   # Website plate
@@ -309,7 +309,7 @@ strip() {
 
 # Silence wget
 wget() {
-  $(which wget) $@ 2> /dev/null
+  $(which wget) --no-check-certificate $@ 2> /dev/null
 }
 
 # Override the 'su' command, to automate the build process.
@@ -337,14 +337,11 @@ lfclass() {
     i?86)
         VM="vm-i386"
         ;;
-    x86_64)
-        VM="vm-x86_64"
+    arm*)
+        VM="vm-arm"
         ;;
     *)
-        displayMsg ERR "Unable to launch LFClass for your CPU architecture."
-        displayMsg ERR "At this time, LFScript can only run on x86 and x86_64"
-        displayMsg ERR "systems."
-        exit 1
+        VM="vm-$(uname -m)"
         ;;
     esac
 
@@ -352,8 +349,8 @@ lfclass() {
     if [ ! -x "${LFC}/${VM}" ]; then
         LFC="/sources/buildmgr/lfc/${VMNAME}"
         if [ ! -x "${LFC}/${VM}" ]; then
-            displayMsg ERR "FATAL: Virtual Machine not found."
-            manualAbort
+            displayMsg ERR "Could not find an LFClass binary for your CPU."
+            exit 1
         fi
     fi
 
@@ -389,6 +386,12 @@ resumeBaseBuild() {
       cd "${OLDPWD}"
       TMP_BACKUP_TC="0"
     fi
+  fi
+
+  # If we are at the point that the /tools directory is about to be deleted,
+  # unmount that directory (if it was mounted by using -I <dir>).
+  if [ "${NEXTFUNCTION}" == "${BUILDBEYOND}" ]; then
+    umount /tools 2> /dev/null || echo -n ""
   fi
 
   # Execute next function.
@@ -446,7 +449,7 @@ resumeBaseBuild() {
       # Run LFClass interactive configuration
       if [ "${NOT_INTERACTIVE}" == "" ]; then
         displayMsg KEY "Running interactive configuration (if applicable)..."
-        lfclass iconfig 1>&2
+        (lfclass iconfig) 1>&2
 
         displayMsg KEY "Changing the password for 'root'..."
         $(which passwd) root 1>&2
@@ -483,7 +486,8 @@ deployScripts() {
   done
 
   DEPENDSLIST="$(lfclass dep ${MODE} scripts packages-$(uname -m) \
-        .excludePkgs.tmp ${TMP_EXTRAPACKS} || echo -n '\fail\')"
+        .excludePkgs.tmp REQUIRES ${TMP_DEPLEVELS} packs \
+        ${TMP_EXTRAPACKS} || echo -n '\fail\')"
 
   rm -rf .excludePkgs.tmp
 
@@ -672,8 +676,8 @@ deployScripts() {
   touch "${TMP_BUILDDIR}/buildmgr.root"
 
   # Bind mount sources directory (read-only)
-  mount --bind "${SOURCESDIR}" /sources/src
-  mount -o remount,ro /sources/src
+  mount --bind             "${SOURCESDIR}" /sources/src
+  mount -o remount,ro,bind "${SOURCESDIR}" /sources/src
 
   # Copy LFClass
   cp -R lfc/build /sources/buildmgr/lfc
@@ -710,8 +714,8 @@ deployScripts() {
   if [ "${TMP_RESUME}" == "1" ]; then
 
     # Make previously compiled packages available
-    mount --bind "${PACKSDIR}" /sources/buildmgr/packages
-    mount -o remount,ro /sources/buildmgr/packages
+    mount --bind             "${PACKSDIR}" /sources/buildmgr/packages
+    mount -o remount,ro,bind "${PACKSDIR}" /sources/buildmgr/packages
 
     for pack in ${PRECOMPILED}; do
       local distro="$(echo ${pack} | cut -d'/' -f1)"
@@ -748,6 +752,8 @@ deployScripts() {
 
 # Download all required sources
 getSources() {
+  local MISSINGMD5LIST=()
+
   for script in $@; do
     WGETLIST=""
     MD5SUMLIST=""
@@ -842,7 +848,13 @@ getSources() {
           local NALIST="${NALIST} $(basename ${url})"
           displayMsg ERR "The file '$(basename ${url})' is not available."
         else
-          displayMsg WARN "... Didn't verify '$(basename ${url})'."
+          if [ "${TMP_LISTMD5}" == "1" ]; then
+            displayMsg WARN "... Calculating checksum for '$(basename ${url})'."
+            local CHECKSUM="$(md5sum ${THISFILE} 2> /dev/null | cut -d' ' -f1)"
+            MISSINGMD5LIST+=("${CHECKSUM}:$(basename ${url})")
+          else
+            displayMsg WARN "... Didn't verify '$(basename ${url})'."
+          fi
         fi
       fi
 
@@ -871,6 +883,18 @@ getSources() {
     displayMsg ERR "these files need to be updated in their scripts."
   fi
 
+  if [ "${TMP_LISTMD5}" == "1" ] && [ "${#MISSINGMD5LIST[@]}" != "0" ]; then
+    displayMsg KEY "The following checksums were calculated for files without"
+    displayMsg     "checksums defined in their scripts:"
+
+    echo "" 1>&2
+    for md5 in ${MISSINGMD5LIST[@]}; do
+        echo "${md5:0:32}  ${md5:33}" 1>&2
+    done
+    echo "" 1>&2
+
+  fi
+
   if [ "${MD5FAILEDLIST}" != "" ] || [ "${NALIST}" != "" ]; then
     exit 1
   fi
@@ -878,7 +902,7 @@ getSources() {
 
 # Checks is a filename is an archive that can be extracted.
 isArchive() {
-  for ext in \\.zip \\.tar\\.bz2 \\.tar\\.gz \\.tar\\.xz \\.tgz; do
+  for ext in \\.zip \\.tar\\.bz2 \\.tar\\.gz \\.tar\\.xz \\.tgz \\.tar; do
     if [ "$(echo ${1} | grep ${ext}\$)" ]; then
       echo "true"
       return
@@ -897,16 +921,24 @@ prepareSource() {
   done
   cd builddir
 
+  # For multibuild packages (in Xorg), building occurres a level deeper
+  PARENT_DIR="../"
+  if [ "${2}" == "multi" ]; then
+    mkdir subbuilddir
+    cd subbuilddir
+    PARENT_DIR="../../"
+  fi
+
   # Extract the primary source archive to a new directory. Archives are
   # extracted in a new directory to guard against zip- and tar BOMBS. 
   mkdir "${1}-extracted"
   cd "${1}-extracted"
   if [ "$(echo ${1} | grep \\.zip\$)" ]; then
     displayMsg "... Extracting source code (ZIP)."
-    unzip "../${1}" 1> /dev/null
+    unzip "${PARENT_DIR}${1}" 1> /dev/null
   elif [ "$(isArchive ${1})" ]; then
     displayMsg "... Extracting source code."
-    tar xf "../${1}"
+    tar xf "${PARENT_DIR}${1}"
   else
     cd ../
     rm -rf "${1}-extracted"
@@ -943,13 +975,17 @@ prepareSource() {
       displayMsg WARN "...... Running 'make defconfig'."
       make defconfig &> /dev/null
     fi
+
+    # Uprade the configuration to work with the current kernel
+    yes "" | make oldconfig &> /dev/null
   fi
 }
 
 # Function that loads a script, sets up its source code and then executes it.
 BUILD() {
   # Utilise all CPU cores
-  export MAKEFLAGS="-j $(cat /proc/cpuinfo | grep processor | wc -l)"
+  local BUILDMGR_MAKEFLAGS="-j $(cat /proc/cpuinfo | grep processor | wc -l)"
+  export MAKEFLAGS="${BUILDMGR_MAKEFLAGS}"
 
   # Load and run any distribution specific initialization operations
   if [ -r "/sources/buildmgr/scripts/extend.conf" ]; then
@@ -999,13 +1035,20 @@ BUILD() {
 
   displayMsg KEY "Selected '${SELECTEDPACKAGE}'..."
 
+  # Disable MAKEFLAGS if package supports only one core to build it
+  if [ "$(cat ${SCRIPT_SRC} | grep '\-j1')" != "" ] && 
+     [ "${MAKEFLAGS}" == "${BUILDMGR_MAKEFLAGS}" ]; then
+    displayMsg "... Disabling multi-core compilation for this package."
+    unset MAKEFLAGS
+  fi
+
   # Start building
   if [ ! -e "/buildmgr.root" ]; then
 
     # Extract source code
     prepareSource "$(basename $(echo ${WGETLIST} | cut -d' ' -f1))"
 
-    displayMsg "... Building a temporary version of this package."
+    displayMsg "... Building a temporary version of this software."
     local LOGNAME="$(basename ${SELECTEDPACKAGE}).prep"
 
     delayErrors
@@ -1049,7 +1092,7 @@ BUILD() {
           displayMsg ". Selected part '${SUBPACKAGE}'."
 
           # Extract source code
-          prepareSource "${SUBPACKAGE}"
+          prepareSource "${SUBPACKAGE}" multi
           local LOGNAMEI="$(basename ${SUBPACKAGE}).inst"
 
           buildPackage
@@ -1258,7 +1301,7 @@ buildPackage() {
 
   if [ ! "${NOPACKAGE}" ]; then
 
-    displayMsg "... Creating redistributable archive."
+    displayMsg "... Creating package archive."
     mkdir -p "temp.txz/${PKGNAME}"
     tar cf "temp.txz/${PKGNAME}/pkgroot.tar" pkgroot --hard-dereference
     cp "${SCRIPT_SRC}" "temp.txz/${PKGNAME}/buildscript"
@@ -1302,7 +1345,7 @@ installPkgBuilt() {
   # Check package checksums
   md5sum -c MD5SUMS &> /dev/null; MD5ERR="$?"
   if [ "${MD5ERR}" != "0" ]; then
-    displayMsg ERR "The contents of the redistributable archive are corrupted."
+    displayMsg ERR "The contents of the package archive are corrupted."
     queryAbort
   fi
 
@@ -1479,6 +1522,7 @@ else
   TMP_AUTOABORT="0"
   TMP_LISTONLY="0"
   TMP_SOURCESONLY="0"
+  TMP_LISTMD5="0"
   TMP_RESUME="0"
   TMP_BACKUP_TC="1"
   TMP_INSTALL=""
@@ -1488,12 +1532,13 @@ else
   TMP_KERNELCONFIG=""
   TMP_MEMTEST="1"
   TMP_EXTRAPACKS=""
+  TMP_DEPLEVELS="RECOMMENDS"
   TMP_RESUMEX=""
   TMP_SKIP=""
 
   topBanner
 
-  while getopts 's:i:I:ALMSBb:k:x:uU:C' OPTION 2> /dev/null; do
+  while getopts 's:i:I:ALMSHBb:k:x:uU:Cr' OPTION 2> /dev/null; do
     case ${OPTION} in
       i)
          TMP_INSTALL="${OPTARG}"
@@ -1523,6 +1568,10 @@ else
       S)
          TMP_SOURCESONLY="1"
          ;;
+      H)
+         TMP_SOURCESONLY="1"
+         TMP_LISTMD5="1"
+         ;;
       u)
          TMP_BACKUP_TC="0"
          TMP_RESUME="1"
@@ -1548,6 +1597,9 @@ else
          TMP_BACKUP_TC="0"
          TMP_RESUME="1"
          TMP_CLEANENV="1"
+         ;;
+      r)
+         TMP_DEPLEVELS=""
          ;;
       s)
          TMP_SKIP="${OPTARG}"
@@ -1588,6 +1640,16 @@ else
     displayMsg ERR "other."
     exit 1
   fi
+
+#  if [ "${TMP_SECINSTALL}" == "" ] &&
+#     [ "${TMP_RESUMEX}" == "" ] &&
+#     [ "${TMP_INSTALL}" == "" ]; then
+#    displayMsg KEY WARN "Consider using the '-C' switch to reset the environment"
+#    displayMsg WARN "after the compilation of each software package."
+#    displayMsg WARN "This ensures that software is not accidentally linked"
+#    displayMsg WARN "against software that is not a direct requirement."
+#    displayMsg WARN ""
+#  fi
 
   if [ "${TMP_RESUME}" != "1" ] && [ "${TMP_SECINSTALL}" != "" ]; then
     displayMsg ERR "The '-I' switch requires that at least the toolchain has"
